<a href="https://colab.research.google.com/github/PrasannaMadiwar/DataWars-Cleaned-Analysis/blob/main/data_collection_using_API'S.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import requests
import pandas as pd


url = "https://imdb236.p.rapidapi.com/api/imdb/top-rated-english-movies"

headers = {
	"x-rapidapi-key": "daba31b3aemsh75df60cbf332969p11cbe5jsna45faec36e50",
	"x-rapidapi-host": "imdb236.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

In [14]:
df = pd.DataFrame(response.json())[['id','primaryTitle','type','startYear','releaseDate','grossWorldwide','isAdult','runtimeMinutes','averageRating','numVotes']]

In [15]:
df

,id,primaryTitle,type,startYear,releaseDate,grossWorldwide,isAdult,runtimeMinutes,averageRating,numVotes
0,tt0111161,The Shawshank Redemption,movie,1994,1994-10-14,2.933374e+07,False,142,9.3,3063006
1,tt0068646,The Godfather,movie,1972,1972-03-24,2.503422e+08,False,175,9.2,2137888
2,tt0468569,The Dark Knight,movie,2008,2008-07-18,1.009057e+09,False,152,9.0,3037363
3,tt0071562,The Godfather Part II,movie,1974,1974-12-18,4.798369e+07,False,202,9.0,1438311
4,tt0050083,12 Angry Men,movie,1957,1957-04-10,2.945000e+03,False,96,9.0,934238
...,...,...,...,...,...,...,...,...,...,...
245,tt1856101,Blade Runner 2049,movie,2017,2017-10-06,2.766060e+08,False,164,8.0,718478
246,tt0063442,Planet of the Apes,movie,1968,1968-04-03,3.260037e+07,False,112,8.0,205684
247,tt0072431,Young Frankenstein,movie,1974,1974-12-15,8.627671e+07,False,106,8.0,176117
248,tt0117666,Sling Blade,movie,1996,1997-03-14,2.444412e+07,False,135,8.0,102257
249,tt0070511,Papillon,movie,1973,1973-12-19,5.326700e+07,False,151,8.0,142729

In [16]:
df.to_csv('Top_250_indian_movies_')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')